### ISSUE TITLE
[NotIssue] Suggestion for improvement based on other project

### ISSUE THREAD

**Issue by b0n3v** [s0h2x/pretty_lootalert#1]
Hello mate, this addon is awesome, but I found similar with feature to show with how much roll you win. Check in please!
https://gitlab.com/Artur91425/LootWonAlert/
https://forum.wowcircle.com/showthread.php?t=1107674&p=7838897

I will wait for your update. Thanks and stay healthy!

![153634568-c4a11f32-63f7-46c9-a7ca-565f3b5560bc](https://user-images.githubusercontent.com/29700572/203601697-f3227751-5f17-46e9-9989-6c66f4b33153.gif)

**Comment by s0h2x** [comment]
Added in v2.0
