### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by zhengyuan-public** [s0h2x/pretty_lootalert#4]
## Can you add options to move the location of alter panel?

I've been using this addon for two weeks and love it. The only problem I had was I couldn't customize the location of the alert panel.

**Comment by zhmtao** [comment]
我也是有同样的问题，不知道该如何移动。

**Comment by s0h2x** [comment]
https://github.com/s0h2x/pretty_lootalert/blob/master/config.lua#L13

**Comment by zhmtao** [comment]
> https://github.com/s0h2x/pretty_lootalert/blob/master/config.lua#L13

ok 我已经修改了  谢谢
